---
- name: Preparing Monitoring Service
  hosts: internal_host
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - defaults/main.yml
                                           
  tasks:
    - include: tasks/monitoring.yml
                                                          
  handlers:
    - include: handlers/main.yml

